### ISSUE TITLE
View folder structure in open/save dialogs

### ISSUE THREAD

**Issue by AlexNav73** [AlexNav73/melos#15]
**TODO:**
- [ ] Add tree view to `OpenFileDialog`
- [ ] Add tree view to `SaveFileDialog`
- [ ] Add filters for files

Use [walkdir](https://github.com/BurntSushi/walkdir) crate to construct folder tree
